name: CI devops 2022 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main #TODO 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-20.04
    steps:
     #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3

     #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        #TODO
        uses: actions/setup-java@v2
        with:   
          java-version: '11'
          distribution: 'adopt'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify -f simple-api/pom.xml #TODO

        
  # define job to build and publish docker image
  build-and-push-docker-image:
  needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-20.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image and push backend
        uses: docker/build-push-action@v2 
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ../../simple-api
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUP_USER}}/tp-devops-epf/simple-api
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main }}

      - name: Build image and push database
          # DO the same for database
          context: ../../database
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUP_USER}}/tp-devops-epf/database
          push: ${{ github.ref == 'refs/heads/main }}


      - name: Build image and push httpd
        # DO the same for httpd
          context: ../../httpd
          tags:  ${{secrets.DOCKER_HUP_USER}}/tp-devops-epf/httpd
          push: ${{ github.ref == 'refs/heads/main }}

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUP_USER }} -p ${{ secrets.DOCKER_HUP_PASSWORD }}

        


